development:
  adapter: mysql2
  database: emails_dev
  username: root
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8

test:
  adapter: mysql2
  database: emails_test
  username: root
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8

production:
  adapter: mysql2
  database: emails_dev
  username: root
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8

staging:
  adapter: mysql2
  database: emails_dev
  username: root
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  encoding: utf8
